#!/bin/bash

echo "🧹 Clearing Laravel caches..."
echo "Please run these commands in the Laravel backend directory:"
echo ""
echo "cd /var/www/mrvl-backend"
echo ""
echo "# Clear application cache"
echo "php artisan cache:clear"
echo ""
echo "# Clear configuration cache"
echo "php artisan config:clear"
echo ""
echo "# Clear route cache"
echo "php artisan route:clear"
echo ""
echo "# Clear view cache"
echo "php artisan view:clear"
echo ""
echo "# Clear compiled services"
echo "php artisan clear-compiled"
echo ""
echo "# Optimize for production (optional)"
echo "php artisan optimize"
echo ""
echo "# Run migrations if needed"
echo "php artisan migrate"
echo ""
echo "# Reload nginx"
echo "sudo systemctl reload nginx"
echo ""
echo "✅ All caches will be cleared and nginx reloaded!"