#!/bin/bash

echo "🚀 Marvel Rivals Deployment Commands"
echo "======================================"
echo ""
echo "✅ Frontend build completed successfully!"
echo ""
echo "📋 Next steps - Run these commands on the server:"
echo ""

echo "🧹 Clear Laravel Caches:"
echo "------------------------"
echo "cd /var/www/mrvl-backend"
echo ""
echo "php artisan cache:clear"
echo "php artisan config:clear"
echo "php artisan route:clear"
echo "php artisan view:clear"
echo "php artisan clear-compiled"
echo ""

echo "🗄️ Run Database Migrations (IMPORTANT!):"
echo "-----------------------------------------"
echo "php artisan migrate"
echo ""
echo "# This enables:"
echo "# - Double elimination brackets"
echo "# - Swiss tournament progression"
echo "# - Group stage tournaments"
echo "# - Third place matches"
echo ""

echo "⚡ Optimize for Production:"
echo "---------------------------"
echo "php artisan optimize"
echo ""

echo "🔄 Reload Nginx:"
echo "----------------"
echo "sudo systemctl reload nginx"
echo "# or"
echo "sudo nginx -s reload"
echo ""

echo "✅ Deployment Complete!"
echo ""
echo "🧪 Test the system:"
echo "• Go to any event page"
echo "• Generate brackets"
echo "• Check rankings page shows flags for all teams"
echo "• Verify bracket progression works"