#!/bin/bash

echo "🔧 Running migration to make team IDs nullable in matches table..."
echo "Note: This script assumes you have access to run migrations on the backend."
echo ""
echo "To apply the migration, run these commands on the backend server:"
echo ""
echo "cd /var/www/mrvl-backend"
echo "php artisan migrate"
echo ""
echo "The migration file is located at:"
echo "/var/www/mrvl-backend/database/migrations/2025_07_23_make_team_ids_nullable_in_matches.php"
echo ""
echo "After running the migration, all tournament formats will work properly:"
echo "✅ Single Elimination"
echo "✅ Double Elimination" 
echo "✅ Round Robin"
echo "✅ Swiss"
echo "✅ Group Stage"